export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_SIGNIN="AUTH_SIGNIN";
export const AUTH_SIGNUP="AUTH_SIGNUP";
export const AUTH_SUBMIT_SUCCESS = "AUTH_SUBMIT_SUCCESS";
export const AUTH_SUBMIT_ERROR = "AUTH_SUBMIT_ERROR";
export const AUTH_SUBMIT_REDIRECT_PATH = "AUTH_SUBMIT_REDIRECT_PATH"

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const EVENT_START = "EVENT_START";
export const EVENT_SUCCESS = "EVENT_SUCCESS";
export const EVENT_FAIL = "EVENT_FAIL";
export const EVENT_SUBMIT = "EVENT_SUBMIT";

export const MY_EVENT_START = "MY_EVENT_START";
export const MY_EVENT_SUCCESS = "MY_EVENT_SUCCESS";
export const MY_EVENT_FAIL = "MY_EVENT_FAIL";
export const MY_EVENT_SUBMIT = "MY_EVENT_SUBMIT";
